name: RailsCamp Germany 2014
description: Updates and announcements for RailsCamp Germany 2014
url: http://2014.railscamp.de/blog
pygments: false
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
encoding: utf-8
